name = "eqsmp"
author = "ODEVJORGE"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a28413caeaa8d3863d951a0f90e418438da85630ae3302e00be84fdc5d734379"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
