name = "eqsmp"
author = "ODEVJORGE"
version = "0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c5bf49a859bedd77a55901095205b4566ea7b21ae49711dc3fb0af330ceddf5"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
