name = "eqsmp"
author = "ODEVJORGE"
version = "0.1.2-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e0716643b6b88b92c6c4fc21aee3350237c75a93c2192473dbb02eb96d369f0"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
