
#Feature Control
["feature control"]
	#Output info into the logs when generating Geolosys deposits
	debugWorldgen = false
	#Outputs really advanced info when generating deposits.
	advancedDebugWorldGen = false
	#Setting this to true will flat out replace all Vein blocks (Copper + Granite Veins and Iron + Tuff Veins)
	# Otherwise, setting to false will allow you to replace vanilla ores associated with ore veins with geolosys equivalents.
	removeVeinOres = false
	#The fallback materials which a Deposit can replace if they're not specified by the deposit itself
	#Format: Comma-delimited set of <modid:block> (see default for example)
	defaultReplacementMaterials = ["minecraft:gravel", "minecraft:dirt", "minecraft:sand", "quark:jasper", "minecraft:stone", "minecraft:andesite", "minecraft:diorite", "minecraft:granite", "minecraft:netherrack", "minecraft:sandstone", "minecraft:deepslate", "minecraft:tuff", "minecraft:calcite", "minecraft:dripstone_block", "minecraft:snow", "minecraft:snow_block", "minecraft:powder_snow", "minecraft:ice", "minecraft:packed_ice", "minecraft:blue_ice", "minecraft:terracotta", "minecraft:white_terracotta", "minecraft:orange_terracotta", "minecraft:magenta_terracotta", "minecraft:light_blue_terracotta", "minecraft:yellow_terracotta", "minecraft:lime_terracotta", "minecraft:pink_terracotta", "minecraft:gray_terracotta", "minecraft:light_gray_terracotta", "minecraft:cyan_terracotta", "minecraft:purple_terracotta", "minecraft:blue_terracotta", "minecraft:brown_terracotta", "minecraft:green_terracotta", "minecraft:red_terracotta", "minecraft:black_terracotta"]

#Prospecting Options
[prospecting]
	#Maximum samples that can generate with each pluton within a chunk
	#Range: 1 ~ 256
	maxSamplesPerChunk = 6
	#The number of times Geolosys will attempt to place plutons in a given chunk
	#Range: > 1
	numPlutonsPerChunk = 2
	#The upper limit of RNG for generating any pluton in a given chunk.
	#Larger values indicate further distance between plutons.
	#Range: 0.0 ~ 1.0
	chunkSkipChance = 0.8
	#Enable the prospector's pickaxe
	enableProPick = true
	#Allow the prospector's pick to get damaged
	enableProPickDmg = false
	#Max durability of a prospector's pick if damage is enabled
	#Range: > 1
	proPickDurability = 1024
	#The range (depth) of the prospector's pick prospecting cycle
	#Range: > 1
	proPickRange = 10
	#The diameter of the prospector's pick prospecting cycle
	#Range: > 1
	proPickDiameter = 23
	#A list of blocks to always ignore when prospecting, even if they're in a deposit.
	proPickDetectionBlacklist = ["minecraft:stone", "minecraft:andesite", "minecraft:diorite", "minecraft:granite", "minecraft:netherrack", "minecraft:sandstone", "minecraft:deepslate", "minecraft:tuff", "minecraft:calcite", "minecraft:dripstone_block"]
	#Give players a Field Manual if they haven't gotten one
	giveManual = true

#Mod-Compat Settings
[compat]
	#This will make it so that Platinum will drop Platinum AND Osmium
	enableOsmium = true
	#This will make it so that Platinum will ONLY drop Osmium
	enableOsmiumExclusively = true
	#This will make it so that Autunite will drop Uranium AND Yellorium
	enableYellorium = true
	#This will make is so that Coal has a rare chance of dropping sulfur
	enableSulfur = true

